Vuologist/bumpie

- client-react/package-lock.json
- client-react/package.json
- client-react/src/common/MediaBreakpoints.js
- client-react/src/common/SettingsSectionHeader.js
- client-react/src/common/ToggleButton.js
- client-react/src/settings/index.js
Resolves #3 
This pull request contains a shift from class to functional component for the use of hooks.
I'll also be opening up an issue for the header alignment. It looks weird when you stretch out the screen. I think the header would look better if the two ends were closer to the respective ends rather than centered in their sections.
> Notify me through... section

- client-react/src/common/Header.js
Added some changes to the header component to space out the header contents more
resolves #18
> spread header out more

- client-react/src/common/Header.js
- client-react/src/common/HeaderDropdown.js
- client-react/src/common/UserLogo.js
- client-react/src/settings/RadioButton.js
Added in a dropdown component and implemented it into the userlogo component (may need to move this elsewhere suggestions would be helpful) Working as of now
> Header dropdown

- guest-gatsby/src/components/DynamicButton.js
- guest-gatsby/src/components/TextInput.js
- guest-gatsby/src/pages/SignIn.js
- package-lock.json
- Installed Gatsby
- Added Button Component copied from React
- Added TextInput Component created using styling in SignIn page
- Removed backend code in SignIn page
- Added responsive styling
Issue #35
> Updated old Login Page

- client-react/src/common/Footer.js
- client-react/src/common/Header.js
- client-react/src/common/HeaderDropdown.js
- client-react/src/settings/index.js
Added responsiveness to the settings page. Header still does not have hamburger menu yet though (not sure if we should wait to approve til then)
> Settings responsiveness

- client-react/src/notification-settings/index.js
> added wrapping from faq

- client-react/src/signin/index.js
> added bumpie logo in and fixed margins

- client-react/package-lock.json
- client-react/package.json
- client-react/src/common/DynamicButton.js
- client-react/src/common/TextInput.js
- client-react/src/config.js
- client-react/src/index.js
- client-react/src/signin/index.js
closes #76 
**Test Instructions:**
**Test 1**
- open chrome console
- enter a random email to the email field
- enter a password such as Password1@ to password field
- enter a same password to confirm password field
if everything worked then you should see nothing.
**Test 2**
- open chrome console
- enter a random email to the email field
- enter a password such as password1@ to password field
- enter a same password to confirm password field
if everything worked then you should see an alert that password does not meet password requirement.
> Feat: add aws sign up call to sign in page

- client-react/package.json
- client-react/src/signin/index.js
- package-lock.json
closes #53
Test Instructions:
Test 1 [successful login]
open chrome console
enter anthonyvu@gmail.com into the email field
enter Passw0rd! into the password field
if everything worked then you should see an alert with the message logged in
Test 2 [bad password]
open chrome console
enter anthonyvu@gmail.com into the email field
enter Pass into the password field
if everything worked then you should see an alert that says incorrect username or password
> Feat: add aws implementation to sign in page

- client-react/package-lock.json
- client-react/package.json
- client-react/src/Routes.js
- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/index.js
closes #91 
Testing Instructions:
- Run bumpie and go to /dashboard 
- Page should load with a category component inside
- Can change title prop in dashboard/index.js to change category title to see if prop is functioning correctly
> Category component

- client-react/src/dashboard/HexagonBox.js
- client-react/src/dashboard/index.js
closes #93 
Test instructions
-Compile
-Go to /dashboard
-Should show title as My Stats as well as placeholder text
> Create hexagon box component

- client-react/src/dashboard/CategoryBox.js
closes #92 
Test Instructions,
-Compile
-Go to /dashboard
-Try using caret to expand and hide information
-if expands should see "PLACE HOLDER FOR REST OF CONTENT" when closed this should be hidden
> added stuff req for show and hide category

- client-react/src/notification-settings/index.js
> Fix: remove text notifications

- client-react/package-lock.json
- client-react/src/App.js
- client-react/src/Routes.js
- client-react/src/authentication/index.js
- client-react/src/common/Header.js
- client-react/src/common/HeaderDropdown.js
- client-react/src/common/HeaderDropdown.test.js
- client-react/src/libs/contextLib.js
closes #101 
closes #63 
Test Instructions:
1. route to dashboard
- login through the sign-in page
- on successful login, u will be redirected to /dashboard
- attempt to sign out by pressing the profile icon and log out. u will be redirected to /sign-in
2. session
- login through the sign-in page
- close your browser
- reopen the browser and go to /dashboard
- you should see the header and footer. if you don't, then that means you are not authenticated
Use these credentials:
anthonyvu@gmail.com
Passw0rd!
> Feat: route to dashboard on login

- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/HexagonBox.js
- client-react/src/dashboard/PentagonBox.js
- client-react/src/dashboard/index.js
Test Instructions:
1. Compile
2. Authenticate and log in
3. Go to /dashboard
4. Should see 5 category boxes and one pentagon box
5. Check to see if hexagon => pentagon
closes #109 
closes #99
> dashboard edits

- client-react/src/authentication/index.js
> fix: resolve display true warning on signin page

- client-react/package-lock.json
- client-react/package.json
- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/Dropdown.js
closes #115 
Testing Instructions
1. Compile
2. Go to /dashboard
3. Click on ellipsis, dropdown should appear
4. Click outside of dropdown, dropdown should disappear
> Dash dropdown menu

- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/SubCategory.js
Closes #122
Testing Instructions:
1. Compile and route to /dashboard
2. Add one subcategory component to a category box
3. Title should match and color of subcategory title should be gray
> Make subcategory title same as category title and grayed out if only 1

- client-react/src/dashboard/CategoryBox.js
> added small change to allow all category boxes to have 1 subcategory

- client-react/package-lock.json
- client-react/package.json
- client-react/src/dashboard/Category.css
- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/SubCategory.js
closes #116
Testing Instructions:
1. Compile and go to /dashboard
2. Open a category box and see if it animates slide out
3. Add a subcategory component with the +  and see if it animates
4. Close category box and see if animates and slides up
> Dashboard animation

- client-react/src/authentication/index.js
- client-react/src/common/DynamicButton.js
- client-react/src/common/TextInput.js
- client-react/src/notification-settings/__snapshots__/RadioButton.test.js.snap
closes #103 
Test instructions:
Note: you might want to create an account and verify your email and another account with an unverified email. if you are on gmail, you can use the technique of periods to create multiple accounts under one email. Such as tk42111@gmail.com and t.k42111@gmail.com. YMMV if using something other than gmail.
please validate that sign in and sign up page confirm to following xd artboards:
- login page
- login page - insert password
- login page - insert email
- login page - invalid email
- login page - invalid password
- login page - email not confirmed
- login page - sign up
- login page - sign up - invalid fields
> Feat: invalid feedback on sign up and login page

- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/Dropdown.js
closes #145 
TESTING INSTRUCTIONS
1. Compile and go to /dashboard
2. Before opening collapsed category component, click on ... and select rename category
- Category component should open and title should now be input box with the old title as placeholder
- Category box should not be able to collapse or open when editing the title
3. Type in any category then hit the save button
4. Refresh page and open collapsed category component
5. Click on ... and select rename category 
6. Rename the category and then hit the save button
> Edit category name

- client-react/src/App.js
- client-react/src/Routes.js
- client-react/src/common/Footer.js
- client-react/src/user-settings/index.js
closes #52 
Test Instructions:
1. navigate to /user-settings
2. verify that layout is similar to User Settings on xd
> Feat: add user-settings page

- client-react/src/dashboard/CategorySummary.js
- client-react/src/dashboard/PentagonBox.js
closes #155
1. Go to /dashboard
2. Compare category summary to Dashboard in xd
> create category summary box ui

- client-react/src/dashboard/CategoryBox.js
> Subcategory one bugfix

- client-react/src/Routes.js
- client-react/src/about-us/index.js
- client-react/src/common/navbar.js
- client-react/src/faq/index.js
- client-react/src/home/index.js
Test instructions:
1. navigate to /
2. navigate to /about-us
2. navigate to /faq
verify that all pages show something similar to xd board
> Feat: reveal public facing pages

- client-react/src/Routes.js
- client-react/src/common/SettingsSectionHeader.js
- client-react/src/common/TextInput.js
- client-react/src/index.css
- client-react/src/libs/validator.js
- client-react/src/user-settings/ChangeEmail.js
closes #139
Test instructions:
1. navigate to /user-settings/email
2. verify against User Settings - Change Email artboards
> Feat: create change email layout

- client-react/package-lock.json
- client-react/package.json
- client-react/src/dashboard/PentagonBox.js
closes #172 
Testing Instructions 
1. npm install 
2. Go to /dashboard
3. Check if hexagon ui matches dashboard in xd (note the ordering of the categories is different, but mainly because of how the package handles it)
> added in hexagon ui and config it to look like design

- client-react/src/Routes.js
- client-react/src/libs/validator.js
- client-react/src/user-settings/ChangePassword.js
closes #140
test instructions:
1. navigate to /user-settings/password
2. verify that page is similar to User Settings - Change Password
> Feat: add change password layout

- client-react/src/Routes.js
- client-react/src/user-settings/ChangeName.js
closes #176
test instructions:
1. navigate to /user-settings/name
2. verify that page is similar to User Settings - Change Username
>  Feat: add change name layout

- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/SubCategory.js
- client-react/src/dashboard/index.js
closes #147 
1. go to /dashboard
2. open any category box and add some subcategories
3. then use delete icon to remove
> Del btn func

- client-react/src/dashboard/CategorySummary.js
- client-react/src/dashboard/PentagonBox.js
- client-react/src/dashboard/index.js
add logic to pass radar data to the pentagon box and to the category summary
closes #156 and closes #170 
Testing Instructions
1. Go to /dashboard
2. Adjust multiple category sliders
3. Check that radar graph adjusts to on slider change
4. Check that percentages move
> Calc Summary Logic + Radar Chart Functionality

- client-react/src/App.js
- client-react/src/common/Footer.js
- client-react/src/common/Header.js
- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/CategorySummary.js
- client-react/src/dashboard/PentagonBox.js
- client-react/src/dashboard/index.js
- client-react/src/notification-settings/index.js
- client-react/src/user-settings/ChangeEmail.js
- client-react/src/user-settings/ChangeName.js
- client-react/src/user-settings/ChangePassword.js
- client-react/src/user-settings/index.js
connect category names to the category summary 
closes #157
Test Instructions
1. Go to /dashboard
2. Edit Category Name
3. Save
4. Check if category name matches with name under category summary
> Connect Category Names with Category Summary/Legend

- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/Dropdown.js
- client-react/src/dashboard/SubCategory.js
- client-react/src/dashboard/index.js
closes #179 
Test Instructions
1. Go to dashboard
2. Add subcategory to one so that there are two 
3. Hit ... and go to edit subcategories
4. Change names and hit save
UX QUESTION: Can users still hit the edit subcategories button if theres only one sub category?
> add editable subcat names

- client-react/src/common/HeaderDropdown.js
- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/Dropdown.js
- client-react/src/dashboard/SubCategory.js
- client-react/src/dashboard/index.js
closes #185 
closes #184 
Testing Instructions
1. Go to /dashboard
2. Add sub categories and edit and change
3. Delete and make sure names get saved
4. Test if header dropdown covers ellipsies
> fix a subcat editing bug & dropdown issue

- client-react/src/dashboard/index.js
> bugfix for subcat bug

- client-react/src/dashboard/CategoryBox.js
- client-react/src/dashboard/index.js
> fix for limit of 5 per subcat

- client-react/src/common/Footer.js
Update footer to match latest XD 
closes #211
> footer updates

- client-react/src/common/navbar.js
> remove header from password-reset

- client-react/src/home/index.js
> fix spacing of text to match xd

- client-react/src/common/navbar.js
> add home link

- client-react/src/common/SettingsSectionHeader.js
- client-react/src/notification-settings/index.js
> updates to notification settings page to match xd

- client-react/src/user-settings/index.js
> user settings fix

- client-react/src/authentication/index.js
fix to look more like xd
closes #226
> Sign in updates

- client-react/src/authentication/index.js
- client-react/src/common/HeaderDropdown.js
- client-react/src/common/navbar.js
- client-react/src/dashboard/CategoryBox.js
- client-react/src/faq/index.js
- client-react/src/home/index.js
- client-react/src/user-settings/index.js
closes #242 
List of changes
Header
- Change sign in link hover effects
- Change header dropdown hover 
- Change header dropdown click to be on box
User Settings Page
- User settings is now on one line
Sign In Page
- Bumpie logo animates on hover
- Button animations
FAQ Page
- Spacing on panels
- Space between header and footer
Home Page
- Get started button font size reduced
> Sprint fixes

- client-react/package-lock.json
- client-react/src/App.js
- client-react/src/authentication/ForgotPassword.js
- client-react/src/authentication/PasswordReset.js
- client-react/src/authentication/SignIn.js
- client-react/src/authentication/SignUp.js
- client-react/src/authentication/SuccessEmailVerified.js
- client-react/src/authentication/SuccessForgotPassword.js
- client-react/src/authentication/index.js
- client-react/src/authentication/style.js
please go through the authentication flow and see if there's anything out of the ordinary
> frontend : refac : broke out authentication index into multiple files

- client-react/src/dashboard/SubCategory.js
- client-react/src/dashboard/index.js
This PR closes #245 and #246 
- Removed code that caused #246 
- Reference error for RC-Slider issue
https://github.com/react-component/slider/issues/433
> Category bug fix

- client-react/src/notification-settings/index.js
> client : feat : remove save reset btn on notif page

- client-react/src/notification-settings/index.js
test instructions
1. sign in
2. go to notification settings
3. verify that your email appears under Notify me through...
> client : feat : notification email reflects user email

- client-react/src/common/HeaderDropdown.js
Peggy had brought this up in our last meeting and I was able to find a solution...
> Fixes Log Out dropdown click

- client-react/src/common/DynamicButton.js
- client-react/src/common/ToggleButton.js
- client-react/src/notification-settings/NotifyMeFrequencySection.js
- client-react/src/notification-settings/index.js
closes #257 
TEST INSTRUCTIONS
1, Go to /notification-settings
2. Toggle the toggle button
> Gray out buttons when notifications is disabled

- client-react/src/user-settings/ChangePassword.js
test instruction:
1. navigate to change password in the user settings page
2. try to change your password
3. try to break the form LOL
> frontend : feat : add ability to change password

- client-react/src/common/Alert.js
- client-react/src/notification-settings/NotifyMeFrequencySection.js
- client-react/src/notification-settings/NotifyMeThroughSection.js
- client-react/src/notification-settings/index.js
closes #253 
TESTING INSTRUCTIONS
1. Go to notification settings
2. Click button on page
3. Alert should appear and disappear in ~3 secs
4. Repeat for all buttons
> Save notification

- client-react/src/Routes.js
- client-react/src/common/navbar.js
> authentication header  fixes

- client-react/public/index.html
> adds fonts import links

- client-react/src/authentication/style.js
> add in styling to fix i forgot my password link 
